@startuml

title ストラテジーパターン

package main {
    object main {
    }
    
}

package Strategy {
    ' 3つのインスタンスだけシングルトンでもつ。VOってやつ？
    ' class Hand{

    ' }
    class Player{
      strategy
      next_hand(arg): void
      win(arg): void
      lose(arg): void
      even(arg): void
    }
    abstract Strategy {
        {abstract} next_hand(arg): void
        {abstract} study(arg): void
    }

    class WinningStrategy {
        next_hand(arg): void
        study(arg): void
    }

    class ProbStrategy {
        next_hand(arg): void
        study(arg): void
    }
}
    main --> Player 
    Player o-right-> Strategy
    WinningStrategy .up.|> Strategy 
    ProbStrategy .up.|> Strategy 
    
    

@enduml